### ISSUE TITLE
Many parsing issues

### ISSUE THREAD

**Issue by mity** [michaelrsweet/mmd#10]
I didn't explore it too deeply but it seems there are many parsing issues, especially (but not only) when containers are nested in a parent container blocks.

For example list nested in a list like this:
```
$ printf '* * * foo' | ./testmmd --only-body
<ul>
<li>* * foo</li>
</ul>
```
or this:
```
$ printf '* foo\n  * bar\n'  | ./testmmd.exe --only-body
<ul>
<li>foo</li>
<li>bar</li>
</ul>
```

or nested blockquotes
```
$ printf '> > > foo' | ./testmmd --only-body
<blockquote>
<p>&gt; &gt; foo</p>
</blockquote>
```

or e.g. a code block (both indented and fenced) embedded in a blockquote:
```
$ printf '> ```\n> foo\n> ```' | ./testmmd --only-body
<blockquote>
<p><code></code><code>
 &gt; foo
 &gt; </code><code></code></p>
</blockquote>
```

similarly for a code block embedded in a list:
```
$ printf '* ```\n  foo\n  ```\n' | ./testmmd.exe --only-body
<ul>
<li><code></code><code>
   foo
   </code><code></code></li>
</ul>
```

There are issues in inline spans, e.g. with an unclosed code span (which generates nonsensically long output so I don't paste it here):
```
$  printf '`' | ./testmmd --only-body | wc -c
8213
```

or when combining both string and ordinary emphasis:
```
$ printf '***foo***'  | ./testmmd --only-body
<p>foo*<strong></strong></p>
```

or when using emphasis inside a link:
```
$ printf '[*a*](url)' | ./testmmd --only-body
<p><a href="url">*a*</a></p>
```

_Originally posted by @mity in https://github.com/michaelrsweet/mmd/pull/9#issuecomment-496080755_

**Comment by michaelrsweet** [comment]
Many parsing issues (arguably for more esoteric markdown "features") have been fixed, using a new "--spec" option with testmmd to validate as much as possible against the current commonmark specification (which also has a bunch of inconsistencies and errors, which are slowly being fixed...)

As of today, "make commonmark" yields 62% correct output, with the bulk of the remaining failures being things like badly formed link references not being passed through as plain text, certain nested list/block stuff not being handled correctly, and edge-case "continuation" text, e.g. blockquote followed by list item without a leading > not parsing the list item into the block quote.

I will continue chipping away at the failure cases, but the point of `mmd` is to be a miniature markdown support library so my focus will remain on supporting common usage and not full conformance with the CommonMark specification.
