### ISSUE TITLE
Support reading markdown from memory

### ISSUE THREAD

**Issue by xdevelnet** [michaelrsweet/mmd#12]
Hello!

I was looking for a markdown library for my own project (in my case I want to convert markdown to html).

So, do you have any options for NOT using files, but memory regions? Thank you and have a nice day!

**Comment by michaelrsweet** [comment]
@xdevelnet For any POSIX-compliant OS, "man fmemopen". But otherwise no I don't provide an equivalent for reading markdown from memory.

**Comment by ell1e** [comment]
For what it's worth this would be particularly interesting for some applications like games that might read from a zip archive or some other type of virtual filesystem that isn't directly extracted on disk.

One easy way to implement this is to simply allow overriding or passing in alternate function pointers for fread, ftell etc., and to make the file pointer some more abstract `void*` pointer that defaults to being a file pointer but with custom functions can refer to whatever the user likes. This way, reading from memory and reading from a file can be handled in a single function without giving up the streaming capabilities.

**Comment by michaelrsweet** [comment]
OK, I ended up adding a mxmlLoadString function for loading from nul-terminated strings:

[master d465bcb Add mmdLoadString API, add root node pointer to other load functions.]

I am looking at adding a mxmlLoadIO function that uses a read callback to eliminate the Windows hack for fmemopen (and the current mmd code should actually work well with this...)

**Comment by michaelrsweet** [comment]
[master 0a2f724] Add mmdLoadIO and use it for reading from strings or files (Issue #12)
