### ISSUE TITLE
emphasis around link is misplaced (mmdutil)

### ISSUE THREAD

**Issue by step-** [michaelrsweet/mmd#15]
CommonMark (cmark) translates this markdown fragment `` *[a](http://example.com "title"   )* `` into HTML `` <p><em><a href="http://example.com" title="title">a</a></em></p> `` while `mmduitl` turns it into `` <p><em></em><a href="http://example.com" title="title">a</a></p> ``, which seems incorrect to me.

**Comment by michaelrsweet** [comment]
This is where nesting of markdown is problematic. I will keep this open to track a potential fix but this is esoteric and there is a simple workaround that (IMHO) is easier to read/parse as a human and is also valid markdown:

    [*a*](http://example.com "title" )

**Comment by step-** [comment]
but it doesn't produce emphasis
```
<p><a href="http://example.com" title="title">*a*</a></p>
```

**Comment by step-** [comment]
I just compare mmdutil and cmark with this bash commands

```bash
md='[*a*](http://example.com "title" )'; mmdutil <(echo $md); cmark <(echo $md)
```

the last four output lines
```
        <p><a href="http://example.com" title="title">*a*</a></p>           <------ mmdutil
         </body>
</html>
<p><a href="http://example.com" title="title"><em>a</em></a></p>            <----- cmark
```

**Comment by michaelrsweet** [comment]
[master 04ee6b0] Fix emphasized or strong text within a link (Issue #15)

**Comment by michaelrsweet** [comment]
[master 23f964e] Fix emphasized or strong text outside a link (Issue #15)
