### ISSUE TITLE
Strikethrough, linebreaks, and underscore support are missing

### ISSUE THREAD

**Issue by timuhl** [michaelrsweet/mmd#4]
I'm not sure if this is intentional, but the following standard markdown functionality is missing:

1) `~~strikethrough~~` isn't implemented
2) `**bold**` and `*italic*` work, but `__bold__` and `_italic_` do not
3) two or more spaces at the end of text line does NOT cause a line break

The code shows some evidence of an intent to (eventually) implement this functionality, but it's not there yet.

**Comment by michaelrsweet** [comment]
@timuhl I used the CommonMark specification as the basis of mmd's markdown support.

1. [x] Strikethrough is a Github extension, but I'm happy to add support for it.
2. [x] Will add support for underscores in addition to asterisks.
3. [x] Will add support for trailing whitespace to insert a line break.

**Comment by michaelrsweet** [comment]
[master 2c6280a] Add support for `__bold__`, `_italic_`, `~~strikethrough~~`, and hard line breaks (Issue #4)
